name: Device configuration files

on:
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Validate config files
        run: |
          for config in revpi_provisioning/devices/PR*.yaml; do
            python3 -m revpi_provisioning.cli.validator $config
          done
